const academicYear = ["Year 1", " Year 2", " Year 3", " Year 4", "Year 5"];

let majors = [
  "Chinese Language",
  "Chinese Studies",
  "English Language",
  "English Literature",
  "Global Studies",
  "History",
  "Japanese Studies",
  "Malay Studies",
  "Philosophy",
  "South Asian Studies",
  "Southeast Asian Studies",
  "Theatre",
  "Anthropology",
  "CNM",
  "Economics",
  "Geography",
  "Political Science",
  "Psychology",
  "Social Work",
  "Sociology",
  "Chemistry",
  "Data Science and Analytics",
  "Life Sciences",
  "Mathematics",
  "Pharmaceutical Science",
  "Physics",
  "Quantitative Finance",
  "Statistics",
  "Architecture",
  "Business Administration",
  "Accountancy",
  "Business Analytics",
  "Computer Engineering",
  "Computer Science",
  "Data Science and Economics",
  "Dentistry",
  "Environmental Studies",
  "Food Science",
  "Industrial Design",
  "Information Security",
  "Information Systems",
  "Landscape Architecture",
  "Law",
  "Medicine",
  "Music",
  "Nursing",
  "Pharmacy",
  "PPE",
  "Real Estate",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Electrical Engineering",
  "Engineering Science",
  "Environmental Engineering",
  "ISE",
  "IPM",
  "MSE",
  "Mechanical Engineering",
  "Others",
];

majors = majors.sort();

export { academicYear, majors };
